function function_Greenspan_PLOTS_mles_with_different_ics

%% For each initial condition (1250, 2500, 5000, 10000)
%% Plot the MLE with different initial radius from each initial condition
%% For example, plot MLE 5000 but vary initial radius for 1250, 2500, 5000,10000

load_file_location = [pwd '\'];

simulation_id = 'Sim7931101';
mle_1250  = load([load_file_location simulation_id '\' simulation_id '_exp_MLE3.mat'],...
    'p_mle');

simulation_id = 'Sim7932101';
mle_2500  = load([load_file_location simulation_id '\' simulation_id '_exp_MLE3.mat'],...
    'p_mle');


simulation_id = 'Sim7933101';
mle_5000  = load([load_file_location simulation_id '\' simulation_id '_exp_MLE3.mat'],...
    'p_mle');


simulation_id = 'Sim7934101';
mle_10000  = load([load_file_location simulation_id '\' simulation_id '_exp_MLE3.mat'],...
    'p_mle');

R0_1250  = mle_1250.p_mle(5);
R0_2500  = mle_2500.p_mle(5);
R0_5000  = mle_5000.p_mle(5);
R0_10000 = mle_10000.p_mle(5);




%% 1) Load the 1250 data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



% 1.1) Plot 1250 data (with initial radius set to 1250 MLE initial radius) against 1250 MLE

simulation_num = 7931101;
parameters_to_profile = 1:5;
disp(['simulation_num is ' num2str(simulation_num)])
disp(['parameters_to_profile is ' num2str(parameters_to_profile)])
load_file_location = [pwd '\'];


[simulation_id, ...
    data_file_to_use_array,...
    data_sheet_to_use_array,...
    p_lower_bounds,...
    p_upper_bounds,...
    p_first_guess,...
    times_to_use,...
    initial_condition,...
    filepath_save,...
    parameter_range_to_profile_custom,...
    parameter_range_to_profile,...
    data_inclusions]  ...
    = function_load_simulation_settings(simulation_num);


load([load_file_location simulation_id '\' simulation_id '_exp_MLE1.mat'],...
    'time_measurements_all',...
    'y_measurements_all',...
    'time_measurements_array',...
    'y_measurements_array',...
    'unique_time_measurements_array',...
    'experimental_measurements_mean_per_timepoint_array',...
    'experimental_measurements_std_per_timepoint_array',...
    'variable_id_measurements',...
    'p_mle',...
    'time_measurements_full_array',...
    'y_measurements_full_array',...
    'unique_time_measurements_full_array',...
    'experimental_measurements_mean_per_timepoint_full_array',...
    'experimental_measurements_std_per_timepoint_full_array',...
    'pooled_standard_deviation_all',...
    'pooled_standard_deviation_outer',...
    'pooled_standard_deviation_necrotic',...
    'pooled_standard_deviation_inhibited'...
    );


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

simulation_id = 'SimData1250MLE1250';

folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end

filepath_save_figs = [load_file_location simulation_id '\'];

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);



%% 1.2) Plot 1250 data (with initial radius set to 2500 MLE initial radius) v 2500 MLE

simulation_id = 'SimData1250MLE2500';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_2500.p_mle;
p_mle(5) = mle_1250.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);

%% 1.3) Plot 1250 data (with initial radius set to 5000 MLE initial radius) v 5000 MLE

simulation_id = 'SimData1250MLE5000';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_5000.p_mle;
p_mle(5) = mle_1250.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);



%% 1.4) Plot 1250 data (with initial radius set to 10000 MLE initial radius) v 10000 MLE


simulation_id = 'SimData1250MLE10000';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_10000.p_mle;
p_mle(5) = mle_1250.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);




%% 2) Load the 2500 MLE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


simulation_num = 7932101;
parameters_to_profile = 1:5;
disp(['simulation_num is ' num2str(simulation_num)])
disp(['parameters_to_profile is ' num2str(parameters_to_profile)])
load_file_location = [pwd '\'];


[simulation_id, ...
    data_file_to_use_array,...
    data_sheet_to_use_array,...
    p_lower_bounds,...
    p_upper_bounds,...
    p_first_guess,...
    times_to_use,...
    initial_condition,...
    filepath_save,...
    parameter_range_to_profile_custom,...
    parameter_range_to_profile,...
    data_inclusions]  ...
    = function_load_simulation_settings(simulation_num);


load([load_file_location simulation_id '\' simulation_id '_exp_MLE2.mat'],...
    'time_measurements_all',...
    'y_measurements_all',...
    'time_measurements_array',...
    'y_measurements_array',...
    'unique_time_measurements_array',...
    'experimental_measurements_mean_per_timepoint_array',...
    'experimental_measurements_std_per_timepoint_array',...
    'variable_id_measurements',...
    'p_mle',...
    'time_measurements_full_array',...
    'y_measurements_full_array',...
    'unique_time_measurements_full_array',...
    'experimental_measurements_mean_per_timepoint_full_array',...
    'experimental_measurements_std_per_timepoint_full_array',...
    'pooled_standard_deviation_all',...
    'pooled_standard_deviation_outer',...
    'pooled_standard_deviation_necrotic',...
    'pooled_standard_deviation_inhibited'...
    );


%% 2.1) Plot 2500 data (with initial radius set to 1250 MLE initial radius) against 1250 MLE


simulation_id = 'SimData2500MLE1250';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_1250.p_mle;
p_mle(5) = mle_2500.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);



%% 2.2) Plot 2500 data (with initial radius set to 2500 MLE initial radius) v 2500 MLE


simulation_id = 'SimData2500MLE2500';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_2500.p_mle;
p_mle(5) = mle_2500.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);

%% 2.3) Plot 2500 data (with initial radius set to 5000 MLE initial radius) v 5000 MLE

simulation_id = 'SimData2500MLE5000';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_5000.p_mle;
p_mle(5) = mle_2500.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);

%% 2.4) Plot 2500 data (with initial radius set to 10000 MLE initial radius) v 10000 MLE


simulation_id = 'SimData2500MLE10000';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_10000.p_mle;
p_mle(5) = mle_2500.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);



%% 3) Load the 5000 data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


simulation_num = 7933101;
parameters_to_profile = 1:5;
disp(['simulation_num is ' num2str(simulation_num)])
disp(['parameters_to_profile is ' num2str(parameters_to_profile)])
load_file_location = [pwd '\'];


[simulation_id, ...
    data_file_to_use_array,...
    data_sheet_to_use_array,...
    p_lower_bounds,...
    p_upper_bounds,...
    p_first_guess,...
    times_to_use,...
    initial_condition,...
    filepath_save,...
    parameter_range_to_profile_custom,...
    parameter_range_to_profile,...
    data_inclusions]  ...
    = function_load_simulation_settings(simulation_num);


load([load_file_location simulation_id '\' simulation_id '_exp_MLE2.mat'],...
    'time_measurements_all',...
    'y_measurements_all',...
    'time_measurements_array',...
    'y_measurements_array',...
    'unique_time_measurements_array',...
    'experimental_measurements_mean_per_timepoint_array',...
    'experimental_measurements_std_per_timepoint_array',...
    'variable_id_measurements',...
    'p_mle',...
    'time_measurements_full_array',...
    'y_measurements_full_array',...
    'unique_time_measurements_full_array',...
    'experimental_measurements_mean_per_timepoint_full_array',...
    'experimental_measurements_std_per_timepoint_full_array',...
    'pooled_standard_deviation_all',...
    'pooled_standard_deviation_outer',...
    'pooled_standard_deviation_necrotic',...
    'pooled_standard_deviation_inhibited'...
    );


%% 3.1) Plot 5000 data (with initial radius set to 1250 MLE initial radius) against 1250 MLE




simulation_id = 'SimData5000MLE1250';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_1250.p_mle;
p_mle(5) = mle_5000.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);



%% 3.2) Plot 5000 data (with initial radius set to 2500 MLE initial radius) v 2500 MLE



simulation_id = 'SimData5000MLE2500';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_2500.p_mle;
p_mle(5) = mle_5000.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);

%% 3.3) Plot 5000 data (with initial radius set to 5000 MLE initial radius) v 5000 MLE

simulation_id = 'SimData5000MLE5000';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_5000.p_mle;
p_mle(5) = mle_5000.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);

%% 3.4) Plot 5000 data (with initial radius set to 10000 MLE initial radius) v 10000 MLE


simulation_id = 'SimData5000MLE10000';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_10000.p_mle;
p_mle(5) = mle_5000.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);




%% 4) Load the 10000 data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


simulation_num = 7934101;
parameters_to_profile = 1:5;
disp(['simulation_num is ' num2str(simulation_num)])
disp(['parameters_to_profile is ' num2str(parameters_to_profile)])
load_file_location = [pwd '\'];


[simulation_id, ...
    data_file_to_use_array,...
    data_sheet_to_use_array,...
    p_lower_bounds,...
    p_upper_bounds,...
    p_first_guess,...
    times_to_use,...
    initial_condition,...
    filepath_save,...
    parameter_range_to_profile_custom,...
    parameter_range_to_profile,...
    data_inclusions]  ...
    = function_load_simulation_settings(simulation_num);


load([load_file_location simulation_id '\' simulation_id '_exp_MLE2.mat'],...
    'time_measurements_all',...
    'y_measurements_all',...
    'time_measurements_array',...
    'y_measurements_array',...
    'unique_time_measurements_array',...
    'experimental_measurements_mean_per_timepoint_array',...
    'experimental_measurements_std_per_timepoint_array',...
    'variable_id_measurements',...
    'p_mle',...
    'time_measurements_full_array',...
    'y_measurements_full_array',...
    'unique_time_measurements_full_array',...
    'experimental_measurements_mean_per_timepoint_full_array',...
    'experimental_measurements_std_per_timepoint_full_array',...
    'pooled_standard_deviation_all',...
    'pooled_standard_deviation_outer',...
    'pooled_standard_deviation_necrotic',...
    'pooled_standard_deviation_inhibited'...
    );


%% 4.1) Plot 10000 data (with initial radius set to 1250 MLE initial radius) against 1250 MLE


simulation_id = 'SimData10000MLE1250';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_1250.p_mle;
p_mle(5) = mle_10000.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);



%% 4.2) Plot 10000 data (with initial radius set to 2500 MLE initial radius) v 2500 MLE


simulation_id = 'SimData10000MLE2500';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_2500.p_mle;
p_mle(5) = mle_10000.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);




%% 4.3) Plot 10000 data (with initial radius set to 5000 MLE initial radius) v 5000 MLE


simulation_id = 'SimData10000MLE5000';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_5000.p_mle;
p_mle(5) = mle_10000.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);




%% 4.4) Plot 10000 data (with initial radius set to 10000 MLE initial radius) v 10000 MLE




simulation_id = 'SimData10000MLE10000';
folder_name = [simulation_id ];
if ~exist([folder_name'], 'dir')
    mkdir([folder_name]);
end


filepath_save_figs = [load_file_location simulation_id '\'];

% Plot

p_mle = mle_10000.p_mle;
p_mle(5) = mle_10000.p_mle(5);

function_Greenspan_PLOTS_v4_expdata_MLE(data_inclusions,time_measurements_all, y_measurements_all,...
    time_measurements_array, y_measurements_array,...
    filepath_save_figs,...
    unique_time_measurements_array,experimental_measurements_mean_per_timepoint_array,...
    experimental_measurements_std_per_timepoint_array,variable_id_measurements,...
    p_mle,time_measurements_full_array,y_measurements_full_array,unique_time_measurements_full_array,...
    experimental_measurements_mean_per_timepoint_full_array,experimental_measurements_std_per_timepoint_full_array,pooled_standard_deviation_all,...
    pooled_standard_deviation_outer,pooled_standard_deviation_necrotic,pooled_standard_deviation_inhibited);




end
